version: "3"
services:
  node:
    container_name: api_express
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - .:/app
    tty:  true
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres_db
    command: "yarn run watch"

  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    volumes:
      - db_data:/var/lib/posrgresql/data

volumes:
  db_data: {}
