version: "3"
services:
  node:
    container_name: api_express
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - .:/app
    tty:  true
    depends_on:
      - mongo
    networks:
      - default
      - kotatsu-network
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: mongodb://dev:dev_pw@mongo:27017/kotatsu
    command: "yarn run quick"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev_pw
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb

volumes:
  db_data: {}

networks:
  kotatsu-network:
    external: true
